---
# tasks file for ansible-role-singularity

 - name: install singularity
   package: 
     name: "{{ item }}"
     state: installed
   with_items: "{{ singularity_packages }}"
   when: singularity_install_package

 - name: template in singularity.conf
   template:
     src: singularity.conf.j2
     dest: "{{ singularity_config_dir }}/singularity.conf"
     backup: yes
     owner: root
     mode: 0644

 - name: template in init if singularity_manage_init_file is True
   template:
     src: init.j2
     dest: "{{ singularity_config_dir }}/init"
     backup: yes
     owner: root
     mode: 0644
   when: singularity_manage_init_file|bool
